
source "virtualbox-iso" "autogenerated_1" {
  boot_wait            = "10s"
  communicator         = "ssh"
  disk_size            = 40000
  guest_additions_mode = "disable"
  guest_os_type        = "Gentoo_64"
  headless             = true
  iso_checksum         = "file:https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso.DIGESTS"
  iso_url              = "https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso"
  memory               = 8192
  shutdown_command     = "shutdown -hP now"
  ssh_username         = "root"
  ssh_port             = 22
  ssh_wait_timeout     = "1800s"
  skip_export          = true
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "ansible" {
    galaxy_file   = "requirements.yml"
    playbook_file = "main.yml"
  }
}
