
source "virtualbox-iso" "autogenerated_1" {
  boot_wait            = "10s"
  boot_command         = ["gentoo dosshd passwd=L4rry_Th3_C0w", "<enter>", "<wait1m>"]
  disk_size            = 40000
  firmware             = "bios"
  guest_additions_mode = "disable"
  guest_os_type        = "Gentoo_64"
  headless             = true
  iso_checksum         = "file:https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso.DIGESTS"
  iso_url              = "https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso"
  memory               = 4096
  shutdown_command     = "poweroff"
  ssh_username         = "root"
  ssh_password         = "L4rry_Th3_C0w"
  ssh_timeout          = "10m"
  ssh_port             = 22
  ssh_agent_auth       = false
  skip_export          = true
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "ansible" {
    user               = "root"
    ansible_env_vars   = ["ANSIBLE_HOST_KEY_CHECKING=false"] 
    extra_arguments    = ["--extra-vars", "ansible_password='L4rry_Th3_C0w'"]
    collections_path   = "requirements.yml"
    playbook_file      = "main.yml"
    use_proxy          = false
  }
}
