
source "virtualbox-iso" "autogenerated_1" {
  boot_wait            = "10s"
  boot_command         = ["gentoo dosshd passwd=vagrant", "<enter>", "<wait1m30s>"]
  disk_size            = 40000
  guest_additions_mode = "disable"
  guest_os_type        = "Gentoo_64"
  headless             = true
  iso_checksum         = "file:https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso.DIGESTS"
  iso_url              = "https://distfiles.gentoo.org/releases/amd64/autobuilds/20220508T170538Z/install-amd64-minimal-20220508T170538Z.iso"
  memory               = 4096
  shutdown_command     = "poweroff"
  ssh_username         = "root"
  ssh_password         = "vagrant"
  ssh_timeout          = "30m"
  ssh_port             = 22
  ssh_agent_auth       = false
  skip_export          = true
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "ansible" {
    collections_path = "requirements.yml"
    playbook_file    = "main.yml"
    use_proxy        = false
  }
}
