---
- name: Enabling password authentication for SSH
  ansible.builtin.lineinfile:
    path: "{{ chroot_mnt }}etc/ssh/sshd_config"
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present

- name: Enabling root login for SSH
  ansible.builtin.lineinfile:
    path: "{{ chroot_mnt }}etc/ssh/sshd_config"
    line: 'PermitRootLogin yes'
    state: present
    insertafter: EOF

- name: Cleaning up Stage 3 tarball
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ chroot_mnt }}{{ stage_tarball }}"
    - "{{ chroot_mnt }}{{ stage_tarball }}.asc"

- name: Unmounting filesystems
  ansible.posix.mount:
    path: "{{ chroot_mnt }}{{ item }}"
    state: unmounted
  ignore_errors: true
  with_items:
    - proc
    - sys
    - dev/pts
    - dev/shm
    - dev
    - boot
    - ''
  loop_control:
    label: "{{ chroot_mnt }}{{ item }}"

- name: Shutting down machine
  community.general.shutdown:
