---
- name: Configuring Grub for UEFI
  ansible.builtin.lineinfile:
    path: "{{ make_conf }}"
    line: GRUB_PLATFORMS="efi-64"
    state: present
    insertafter: EOF
  when: efivars_contents.stdout != ""

- name: Emerging Grub
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; emerge sys-boot/grub'"

- name: Installing Grub for BIOS
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; grub-install {{ sys_device }}'"
  when: efivars_contents.stdout == ""

- name: Installing Grub for UEFI
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; grub-install --target=x86_64-efi --efi-directory=/boot --removable'"
  when: efivars_contents.stdout != ""

- name: Updating Grub
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; grub-mkconfig -o /boot/grub/grub.cfg'"
