---
name: CI

on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix any “Too many open files” errors
        run: sudo launchctl limit maxfiles unlimited

      - name: Install Ansible
        run: python -m pip install ansible

      - name: Install sshpass
        run: brew install esolitos/ipa/sshpass

      - name: Test playbook
        run: packer build packer.pkr.hcl
        env:
          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
          PACKER_LOG: 1
