---
name: CI

on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix any “Too many open files” errors
        run: sudo launchctl limit maxfiles unlimited

      - name: Install Ansible
        run: brew install ansible

      - name: Install sshpass
        run: brew install esolitos/ipa/sshpass

      - name: Test playbook
        run: packer build packer.pkr.hcl
        env:
          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
          PACKER_LOG: 1

      - name: Jira login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue if success
        uses: atlassian/gajira-create@master
        if: success()
        with:
          project: GLP
          issuetype: Build
          summary: |
            Build completed for ${{ github.repository }}

      - name: Create Jira issue if failed
        uses: atlassian/gajira-create@master
        if: failure()
        with:
          project: GLP
          issuetype: Build
          summary: |
            Build failed for ${{ github.repository }}
