---
name: CI

on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install Ansible
        run: python3 -m pip install ansible

      - name: Install sshpass
        run: brew install esolitos/ipa/sshpass

      - name: Prevent MacOS crash
        run: export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

      - name: Debug
        run: export PACKER_LOG=1

      - name: Test playbook
        run: packer build packer.pkr.hcl
